// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sharpa_hand.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sharpa_5fhand_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sharpa_5fhand_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sharpa_5fhand_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sharpa_5fhand_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sharpa_5fhand_2eproto;
namespace proto {
class HandAction;
class HandActionDefaultTypeInternal;
extern HandActionDefaultTypeInternal _HandAction_default_instance_;
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class Joint;
class JointDefaultTypeInternal;
extern JointDefaultTypeInternal _Joint_default_instance_;
class MocapKeypoints;
class MocapKeypointsDefaultTypeInternal;
extern MocapKeypointsDefaultTypeInternal _MocapKeypoints_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class Pose;
class PoseDefaultTypeInternal;
extern PoseDefaultTypeInternal _Pose_default_instance_;
class Quaternion;
class QuaternionDefaultTypeInternal;
extern QuaternionDefaultTypeInternal _Quaternion_default_instance_;
class Stamp;
class StampDefaultTypeInternal;
extern StampDefaultTypeInternal _Stamp_default_instance_;
}  // namespace proto
PROTOBUF_NAMESPACE_OPEN
template<> ::proto::HandAction* Arena::CreateMaybeMessage<::proto::HandAction>(Arena*);
template<> ::proto::Header* Arena::CreateMaybeMessage<::proto::Header>(Arena*);
template<> ::proto::Joint* Arena::CreateMaybeMessage<::proto::Joint>(Arena*);
template<> ::proto::MocapKeypoints* Arena::CreateMaybeMessage<::proto::MocapKeypoints>(Arena*);
template<> ::proto::Point* Arena::CreateMaybeMessage<::proto::Point>(Arena*);
template<> ::proto::Pose* Arena::CreateMaybeMessage<::proto::Pose>(Arena*);
template<> ::proto::Quaternion* Arena::CreateMaybeMessage<::proto::Quaternion>(Arena*);
template<> ::proto::Stamp* Arena::CreateMaybeMessage<::proto::Stamp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace proto {

// ===================================================================

class Stamp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Stamp) */ {
 public:
  inline Stamp() : Stamp(nullptr) {};
  virtual ~Stamp();

  Stamp(const Stamp& from);
  Stamp(Stamp&& from) noexcept
    : Stamp() {
    *this = ::std::move(from);
  }

  inline Stamp& operator=(const Stamp& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stamp& operator=(Stamp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Stamp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Stamp* internal_default_instance() {
    return reinterpret_cast<const Stamp*>(
               &_Stamp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Stamp& a, Stamp& b) {
    a.Swap(&b);
  }
  inline void Swap(Stamp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stamp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Stamp* New() const final {
    return CreateMaybeMessage<Stamp>(nullptr);
  }

  Stamp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Stamp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Stamp& from);
  void MergeFrom(const Stamp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Stamp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Stamp";
  }
  protected:
  explicit Stamp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharpa_5fhand_2eproto);
    return ::descriptor_table_sharpa_5fhand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSecFieldNumber = 1,
    kNanosecFieldNumber = 2,
  };
  // int32 sec = 1;
  void clear_sec();
  ::PROTOBUF_NAMESPACE_ID::int32 sec() const;
  void set_sec(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sec() const;
  void _internal_set_sec(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 nanosec = 2;
  void clear_nanosec();
  ::PROTOBUF_NAMESPACE_ID::int32 nanosec() const;
  void set_nanosec(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nanosec() const;
  void _internal_set_nanosec(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:proto.Stamp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 sec_;
  ::PROTOBUF_NAMESPACE_ID::int32 nanosec_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharpa_5fhand_2eproto;
};
// -------------------------------------------------------------------

class Header PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Header) */ {
 public:
  inline Header() : Header(nullptr) {};
  virtual ~Header();

  Header(const Header& from);
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  inline Header& operator=(Header&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }
  inline void Swap(Header* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Header* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const final {
    return CreateMaybeMessage<Header>(nullptr);
  }

  Header* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Header* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Header";
  }
  protected:
  explicit Header(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharpa_5fhand_2eproto);
    return ::descriptor_table_sharpa_5fhand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameIdFieldNumber = 2,
    kStampFieldNumber = 1,
  };
  // string frame_id = 2;
  void clear_frame_id();
  const std::string& frame_id() const;
  void set_frame_id(const std::string& value);
  void set_frame_id(std::string&& value);
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  std::string* mutable_frame_id();
  std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_frame_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_frame_id(
      std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // .proto.Stamp stamp = 1;
  bool has_stamp() const;
  private:
  bool _internal_has_stamp() const;
  public:
  void clear_stamp();
  const ::proto::Stamp& stamp() const;
  ::proto::Stamp* release_stamp();
  ::proto::Stamp* mutable_stamp();
  void set_allocated_stamp(::proto::Stamp* stamp);
  private:
  const ::proto::Stamp& _internal_stamp() const;
  ::proto::Stamp* _internal_mutable_stamp();
  public:
  void unsafe_arena_set_allocated_stamp(
      ::proto::Stamp* stamp);
  ::proto::Stamp* unsafe_arena_release_stamp();

  // @@protoc_insertion_point(class_scope:proto.Header)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
  ::proto::Stamp* stamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharpa_5fhand_2eproto;
};
// -------------------------------------------------------------------

class Point PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Point) */ {
 public:
  inline Point() : Point(nullptr) {};
  virtual ~Point();

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Point* New() const final {
    return CreateMaybeMessage<Point>(nullptr);
  }

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharpa_5fhand_2eproto);
    return ::descriptor_table_sharpa_5fhand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:proto.Point)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharpa_5fhand_2eproto;
};
// -------------------------------------------------------------------

class Quaternion PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Quaternion) */ {
 public:
  inline Quaternion() : Quaternion(nullptr) {};
  virtual ~Quaternion();

  Quaternion(const Quaternion& from);
  Quaternion(Quaternion&& from) noexcept
    : Quaternion() {
    *this = ::std::move(from);
  }

  inline Quaternion& operator=(const Quaternion& from) {
    CopyFrom(from);
    return *this;
  }
  inline Quaternion& operator=(Quaternion&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Quaternion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Quaternion* internal_default_instance() {
    return reinterpret_cast<const Quaternion*>(
               &_Quaternion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Quaternion& a, Quaternion& b) {
    a.Swap(&b);
  }
  inline void Swap(Quaternion* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Quaternion* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Quaternion* New() const final {
    return CreateMaybeMessage<Quaternion>(nullptr);
  }

  Quaternion* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Quaternion>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Quaternion& from);
  void MergeFrom(const Quaternion& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Quaternion* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Quaternion";
  }
  protected:
  explicit Quaternion(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharpa_5fhand_2eproto);
    return ::descriptor_table_sharpa_5fhand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
  };
  // float w = 1;
  void clear_w();
  float w() const;
  void set_w(float value);
  private:
  float _internal_w() const;
  void _internal_set_w(float value);
  public:

  // float x = 2;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 3;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 4;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:proto.Quaternion)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float w_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharpa_5fhand_2eproto;
};
// -------------------------------------------------------------------

class Pose PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Pose) */ {
 public:
  inline Pose() : Pose(nullptr) {};
  virtual ~Pose();

  Pose(const Pose& from);
  Pose(Pose&& from) noexcept
    : Pose() {
    *this = ::std::move(from);
  }

  inline Pose& operator=(const Pose& from) {
    CopyFrom(from);
    return *this;
  }
  inline Pose& operator=(Pose&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Pose& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Pose* internal_default_instance() {
    return reinterpret_cast<const Pose*>(
               &_Pose_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Pose& a, Pose& b) {
    a.Swap(&b);
  }
  inline void Swap(Pose* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Pose* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Pose* New() const final {
    return CreateMaybeMessage<Pose>(nullptr);
  }

  Pose* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Pose>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Pose& from);
  void MergeFrom(const Pose& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Pose* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Pose";
  }
  protected:
  explicit Pose(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharpa_5fhand_2eproto);
    return ::descriptor_table_sharpa_5fhand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kOrientationFieldNumber = 2,
  };
  // .proto.Point position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::proto::Point& position() const;
  ::proto::Point* release_position();
  ::proto::Point* mutable_position();
  void set_allocated_position(::proto::Point* position);
  private:
  const ::proto::Point& _internal_position() const;
  ::proto::Point* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::proto::Point* position);
  ::proto::Point* unsafe_arena_release_position();

  // .proto.Quaternion orientation = 2;
  bool has_orientation() const;
  private:
  bool _internal_has_orientation() const;
  public:
  void clear_orientation();
  const ::proto::Quaternion& orientation() const;
  ::proto::Quaternion* release_orientation();
  ::proto::Quaternion* mutable_orientation();
  void set_allocated_orientation(::proto::Quaternion* orientation);
  private:
  const ::proto::Quaternion& _internal_orientation() const;
  ::proto::Quaternion* _internal_mutable_orientation();
  public:
  void unsafe_arena_set_allocated_orientation(
      ::proto::Quaternion* orientation);
  ::proto::Quaternion* unsafe_arena_release_orientation();

  // @@protoc_insertion_point(class_scope:proto.Pose)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::proto::Point* position_;
  ::proto::Quaternion* orientation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharpa_5fhand_2eproto;
};
// -------------------------------------------------------------------

class Joint PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Joint) */ {
 public:
  inline Joint() : Joint(nullptr) {};
  virtual ~Joint();

  Joint(const Joint& from);
  Joint(Joint&& from) noexcept
    : Joint() {
    *this = ::std::move(from);
  }

  inline Joint& operator=(const Joint& from) {
    CopyFrom(from);
    return *this;
  }
  inline Joint& operator=(Joint&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Joint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Joint* internal_default_instance() {
    return reinterpret_cast<const Joint*>(
               &_Joint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Joint& a, Joint& b) {
    a.Swap(&b);
  }
  inline void Swap(Joint* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Joint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Joint* New() const final {
    return CreateMaybeMessage<Joint>(nullptr);
  }

  Joint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Joint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Joint& from);
  void MergeFrom(const Joint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Joint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Joint";
  }
  protected:
  explicit Joint(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharpa_5fhand_2eproto);
    return ::descriptor_table_sharpa_5fhand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPositionFieldNumber = 2,
  };
  // repeated string name = 1;
  int name_size() const;
  private:
  int _internal_name_size() const;
  public:
  void clear_name();
  const std::string& name(int index) const;
  std::string* mutable_name(int index);
  void set_name(int index, const std::string& value);
  void set_name(int index, std::string&& value);
  void set_name(int index, const char* value);
  void set_name(int index, const char* value, size_t size);
  std::string* add_name();
  void add_name(const std::string& value);
  void add_name(std::string&& value);
  void add_name(const char* value);
  void add_name(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_name();
  private:
  const std::string& _internal_name(int index) const;
  std::string* _internal_add_name();
  public:

  // repeated float position = 2;
  int position_size() const;
  private:
  int _internal_position_size() const;
  public:
  void clear_position();
  private:
  float _internal_position(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_position() const;
  void _internal_add_position(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_position();
  public:
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      position() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_position();

  // @@protoc_insertion_point(class_scope:proto.Joint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> name_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > position_;
  mutable std::atomic<int> _position_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharpa_5fhand_2eproto;
};
// -------------------------------------------------------------------

class MocapKeypoints PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.MocapKeypoints) */ {
 public:
  inline MocapKeypoints() : MocapKeypoints(nullptr) {};
  virtual ~MocapKeypoints();

  MocapKeypoints(const MocapKeypoints& from);
  MocapKeypoints(MocapKeypoints&& from) noexcept
    : MocapKeypoints() {
    *this = ::std::move(from);
  }

  inline MocapKeypoints& operator=(const MocapKeypoints& from) {
    CopyFrom(from);
    return *this;
  }
  inline MocapKeypoints& operator=(MocapKeypoints&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MocapKeypoints& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MocapKeypoints* internal_default_instance() {
    return reinterpret_cast<const MocapKeypoints*>(
               &_MocapKeypoints_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(MocapKeypoints& a, MocapKeypoints& b) {
    a.Swap(&b);
  }
  inline void Swap(MocapKeypoints* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MocapKeypoints* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MocapKeypoints* New() const final {
    return CreateMaybeMessage<MocapKeypoints>(nullptr);
  }

  MocapKeypoints* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MocapKeypoints>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MocapKeypoints& from);
  void MergeFrom(const MocapKeypoints& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MocapKeypoints* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.MocapKeypoints";
  }
  protected:
  explicit MocapKeypoints(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharpa_5fhand_2eproto);
    return ::descriptor_table_sharpa_5fhand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLeftMocapPoseFieldNumber = 2,
    kRightMocapPoseFieldNumber = 3,
    kHeaderFieldNumber = 1,
  };
  // repeated .proto.Pose left_mocap_pose = 2;
  int left_mocap_pose_size() const;
  private:
  int _internal_left_mocap_pose_size() const;
  public:
  void clear_left_mocap_pose();
  ::proto::Pose* mutable_left_mocap_pose(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose >*
      mutable_left_mocap_pose();
  private:
  const ::proto::Pose& _internal_left_mocap_pose(int index) const;
  ::proto::Pose* _internal_add_left_mocap_pose();
  public:
  const ::proto::Pose& left_mocap_pose(int index) const;
  ::proto::Pose* add_left_mocap_pose();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose >&
      left_mocap_pose() const;

  // repeated .proto.Pose right_mocap_pose = 3;
  int right_mocap_pose_size() const;
  private:
  int _internal_right_mocap_pose_size() const;
  public:
  void clear_right_mocap_pose();
  ::proto::Pose* mutable_right_mocap_pose(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose >*
      mutable_right_mocap_pose();
  private:
  const ::proto::Pose& _internal_right_mocap_pose(int index) const;
  ::proto::Pose* _internal_add_right_mocap_pose();
  public:
  const ::proto::Pose& right_mocap_pose(int index) const;
  ::proto::Pose* add_right_mocap_pose();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose >&
      right_mocap_pose() const;

  // .proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::proto::Header& header() const;
  ::proto::Header* release_header();
  ::proto::Header* mutable_header();
  void set_allocated_header(::proto::Header* header);
  private:
  const ::proto::Header& _internal_header() const;
  ::proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::proto::Header* header);
  ::proto::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:proto.MocapKeypoints)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose > left_mocap_pose_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose > right_mocap_pose_;
  ::proto::Header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharpa_5fhand_2eproto;
};
// -------------------------------------------------------------------

class HandAction PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.HandAction) */ {
 public:
  inline HandAction() : HandAction(nullptr) {};
  virtual ~HandAction();

  HandAction(const HandAction& from);
  HandAction(HandAction&& from) noexcept
    : HandAction() {
    *this = ::std::move(from);
  }

  inline HandAction& operator=(const HandAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline HandAction& operator=(HandAction&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const HandAction& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HandAction* internal_default_instance() {
    return reinterpret_cast<const HandAction*>(
               &_HandAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(HandAction& a, HandAction& b) {
    a.Swap(&b);
  }
  inline void Swap(HandAction* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HandAction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline HandAction* New() const final {
    return CreateMaybeMessage<HandAction>(nullptr);
  }

  HandAction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<HandAction>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const HandAction& from);
  void MergeFrom(const HandAction& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HandAction* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.HandAction";
  }
  protected:
  explicit HandAction(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharpa_5fhand_2eproto);
    return ::descriptor_table_sharpa_5fhand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kJointLeftFieldNumber = 2,
    kJointRightFieldNumber = 3,
  };
  // .proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::proto::Header& header() const;
  ::proto::Header* release_header();
  ::proto::Header* mutable_header();
  void set_allocated_header(::proto::Header* header);
  private:
  const ::proto::Header& _internal_header() const;
  ::proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::proto::Header* header);
  ::proto::Header* unsafe_arena_release_header();

  // .proto.Joint joint_left = 2;
  bool has_joint_left() const;
  private:
  bool _internal_has_joint_left() const;
  public:
  void clear_joint_left();
  const ::proto::Joint& joint_left() const;
  ::proto::Joint* release_joint_left();
  ::proto::Joint* mutable_joint_left();
  void set_allocated_joint_left(::proto::Joint* joint_left);
  private:
  const ::proto::Joint& _internal_joint_left() const;
  ::proto::Joint* _internal_mutable_joint_left();
  public:
  void unsafe_arena_set_allocated_joint_left(
      ::proto::Joint* joint_left);
  ::proto::Joint* unsafe_arena_release_joint_left();

  // .proto.Joint joint_right = 3;
  bool has_joint_right() const;
  private:
  bool _internal_has_joint_right() const;
  public:
  void clear_joint_right();
  const ::proto::Joint& joint_right() const;
  ::proto::Joint* release_joint_right();
  ::proto::Joint* mutable_joint_right();
  void set_allocated_joint_right(::proto::Joint* joint_right);
  private:
  const ::proto::Joint& _internal_joint_right() const;
  ::proto::Joint* _internal_mutable_joint_right();
  public:
  void unsafe_arena_set_allocated_joint_right(
      ::proto::Joint* joint_right);
  ::proto::Joint* unsafe_arena_release_joint_right();

  // @@protoc_insertion_point(class_scope:proto.HandAction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::proto::Header* header_;
  ::proto::Joint* joint_left_;
  ::proto::Joint* joint_right_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharpa_5fhand_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Stamp

// int32 sec = 1;
inline void Stamp::clear_sec() {
  sec_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Stamp::_internal_sec() const {
  return sec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Stamp::sec() const {
  // @@protoc_insertion_point(field_get:proto.Stamp.sec)
  return _internal_sec();
}
inline void Stamp::_internal_set_sec(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sec_ = value;
}
inline void Stamp::set_sec(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sec(value);
  // @@protoc_insertion_point(field_set:proto.Stamp.sec)
}

// int32 nanosec = 2;
inline void Stamp::clear_nanosec() {
  nanosec_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Stamp::_internal_nanosec() const {
  return nanosec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Stamp::nanosec() const {
  // @@protoc_insertion_point(field_get:proto.Stamp.nanosec)
  return _internal_nanosec();
}
inline void Stamp::_internal_set_nanosec(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nanosec_ = value;
}
inline void Stamp::set_nanosec(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nanosec(value);
  // @@protoc_insertion_point(field_set:proto.Stamp.nanosec)
}

// -------------------------------------------------------------------

// Header

// .proto.Stamp stamp = 1;
inline bool Header::_internal_has_stamp() const {
  return this != internal_default_instance() && stamp_ != nullptr;
}
inline bool Header::has_stamp() const {
  return _internal_has_stamp();
}
inline void Header::clear_stamp() {
  if (GetArena() == nullptr && stamp_ != nullptr) {
    delete stamp_;
  }
  stamp_ = nullptr;
}
inline const ::proto::Stamp& Header::_internal_stamp() const {
  const ::proto::Stamp* p = stamp_;
  return p != nullptr ? *p : *reinterpret_cast<const ::proto::Stamp*>(
      &::proto::_Stamp_default_instance_);
}
inline const ::proto::Stamp& Header::stamp() const {
  // @@protoc_insertion_point(field_get:proto.Header.stamp)
  return _internal_stamp();
}
inline void Header::unsafe_arena_set_allocated_stamp(
    ::proto::Stamp* stamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stamp_);
  }
  stamp_ = stamp;
  if (stamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.Header.stamp)
}
inline ::proto::Stamp* Header::release_stamp() {
  auto temp = unsafe_arena_release_stamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::proto::Stamp* Header::unsafe_arena_release_stamp() {
  // @@protoc_insertion_point(field_release:proto.Header.stamp)
  
  ::proto::Stamp* temp = stamp_;
  stamp_ = nullptr;
  return temp;
}
inline ::proto::Stamp* Header::_internal_mutable_stamp() {
  
  if (stamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::Stamp>(GetArena());
    stamp_ = p;
  }
  return stamp_;
}
inline ::proto::Stamp* Header::mutable_stamp() {
  // @@protoc_insertion_point(field_mutable:proto.Header.stamp)
  return _internal_mutable_stamp();
}
inline void Header::set_allocated_stamp(::proto::Stamp* stamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete stamp_;
  }
  if (stamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(stamp);
    if (message_arena != submessage_arena) {
      stamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stamp, submessage_arena);
    }
    
  } else {
    
  }
  stamp_ = stamp;
  // @@protoc_insertion_point(field_set_allocated:proto.Header.stamp)
}

// string frame_id = 2;
inline void Header::clear_frame_id() {
  frame_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Header::frame_id() const {
  // @@protoc_insertion_point(field_get:proto.Header.frame_id)
  return _internal_frame_id();
}
inline void Header::set_frame_id(const std::string& value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:proto.Header.frame_id)
}
inline std::string* Header::mutable_frame_id() {
  // @@protoc_insertion_point(field_mutable:proto.Header.frame_id)
  return _internal_mutable_frame_id();
}
inline const std::string& Header::_internal_frame_id() const {
  return frame_id_.Get();
}
inline void Header::_internal_set_frame_id(const std::string& value) {
  
  frame_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Header::set_frame_id(std::string&& value) {
  
  frame_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:proto.Header.frame_id)
}
inline void Header::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  frame_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:proto.Header.frame_id)
}
inline void Header::set_frame_id(const char* value,
    size_t size) {
  
  frame_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:proto.Header.frame_id)
}
inline std::string* Header::_internal_mutable_frame_id() {
  
  return frame_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Header::release_frame_id() {
  // @@protoc_insertion_point(field_release:proto.Header.frame_id)
  return frame_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Header::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    
  } else {
    
  }
  frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:proto.Header.frame_id)
}
inline std::string* Header::unsafe_arena_release_frame_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:proto.Header.frame_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return frame_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Header::unsafe_arena_set_allocated_frame_id(
    std::string* frame_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (frame_id != nullptr) {
    
  } else {
    
  }
  frame_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      frame_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.Header.frame_id)
}

// -------------------------------------------------------------------

// Point

// float x = 1;
inline void Point::clear_x() {
  x_ = 0;
}
inline float Point::_internal_x() const {
  return x_;
}
inline float Point::x() const {
  // @@protoc_insertion_point(field_get:proto.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Point::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:proto.Point.x)
}

// float y = 2;
inline void Point::clear_y() {
  y_ = 0;
}
inline float Point::_internal_y() const {
  return y_;
}
inline float Point::y() const {
  // @@protoc_insertion_point(field_get:proto.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Point::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:proto.Point.y)
}

// float z = 3;
inline void Point::clear_z() {
  z_ = 0;
}
inline float Point::_internal_z() const {
  return z_;
}
inline float Point::z() const {
  // @@protoc_insertion_point(field_get:proto.Point.z)
  return _internal_z();
}
inline void Point::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Point::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:proto.Point.z)
}

// -------------------------------------------------------------------

// Quaternion

// float w = 1;
inline void Quaternion::clear_w() {
  w_ = 0;
}
inline float Quaternion::_internal_w() const {
  return w_;
}
inline float Quaternion::w() const {
  // @@protoc_insertion_point(field_get:proto.Quaternion.w)
  return _internal_w();
}
inline void Quaternion::_internal_set_w(float value) {
  
  w_ = value;
}
inline void Quaternion::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:proto.Quaternion.w)
}

// float x = 2;
inline void Quaternion::clear_x() {
  x_ = 0;
}
inline float Quaternion::_internal_x() const {
  return x_;
}
inline float Quaternion::x() const {
  // @@protoc_insertion_point(field_get:proto.Quaternion.x)
  return _internal_x();
}
inline void Quaternion::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Quaternion::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:proto.Quaternion.x)
}

// float y = 3;
inline void Quaternion::clear_y() {
  y_ = 0;
}
inline float Quaternion::_internal_y() const {
  return y_;
}
inline float Quaternion::y() const {
  // @@protoc_insertion_point(field_get:proto.Quaternion.y)
  return _internal_y();
}
inline void Quaternion::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Quaternion::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:proto.Quaternion.y)
}

// float z = 4;
inline void Quaternion::clear_z() {
  z_ = 0;
}
inline float Quaternion::_internal_z() const {
  return z_;
}
inline float Quaternion::z() const {
  // @@protoc_insertion_point(field_get:proto.Quaternion.z)
  return _internal_z();
}
inline void Quaternion::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Quaternion::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:proto.Quaternion.z)
}

// -------------------------------------------------------------------

// Pose

// .proto.Point position = 1;
inline bool Pose::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool Pose::has_position() const {
  return _internal_has_position();
}
inline void Pose::clear_position() {
  if (GetArena() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::proto::Point& Pose::_internal_position() const {
  const ::proto::Point* p = position_;
  return p != nullptr ? *p : *reinterpret_cast<const ::proto::Point*>(
      &::proto::_Point_default_instance_);
}
inline const ::proto::Point& Pose::position() const {
  // @@protoc_insertion_point(field_get:proto.Pose.position)
  return _internal_position();
}
inline void Pose::unsafe_arena_set_allocated_position(
    ::proto::Point* position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.Pose.position)
}
inline ::proto::Point* Pose::release_position() {
  auto temp = unsafe_arena_release_position();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::proto::Point* Pose::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:proto.Pose.position)
  
  ::proto::Point* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::proto::Point* Pose::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::Point>(GetArena());
    position_ = p;
  }
  return position_;
}
inline ::proto::Point* Pose::mutable_position() {
  // @@protoc_insertion_point(field_mutable:proto.Pose.position)
  return _internal_mutable_position();
}
inline void Pose::set_allocated_position(::proto::Point* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:proto.Pose.position)
}

// .proto.Quaternion orientation = 2;
inline bool Pose::_internal_has_orientation() const {
  return this != internal_default_instance() && orientation_ != nullptr;
}
inline bool Pose::has_orientation() const {
  return _internal_has_orientation();
}
inline void Pose::clear_orientation() {
  if (GetArena() == nullptr && orientation_ != nullptr) {
    delete orientation_;
  }
  orientation_ = nullptr;
}
inline const ::proto::Quaternion& Pose::_internal_orientation() const {
  const ::proto::Quaternion* p = orientation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::proto::Quaternion*>(
      &::proto::_Quaternion_default_instance_);
}
inline const ::proto::Quaternion& Pose::orientation() const {
  // @@protoc_insertion_point(field_get:proto.Pose.orientation)
  return _internal_orientation();
}
inline void Pose::unsafe_arena_set_allocated_orientation(
    ::proto::Quaternion* orientation) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(orientation_);
  }
  orientation_ = orientation;
  if (orientation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.Pose.orientation)
}
inline ::proto::Quaternion* Pose::release_orientation() {
  auto temp = unsafe_arena_release_orientation();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::proto::Quaternion* Pose::unsafe_arena_release_orientation() {
  // @@protoc_insertion_point(field_release:proto.Pose.orientation)
  
  ::proto::Quaternion* temp = orientation_;
  orientation_ = nullptr;
  return temp;
}
inline ::proto::Quaternion* Pose::_internal_mutable_orientation() {
  
  if (orientation_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::Quaternion>(GetArena());
    orientation_ = p;
  }
  return orientation_;
}
inline ::proto::Quaternion* Pose::mutable_orientation() {
  // @@protoc_insertion_point(field_mutable:proto.Pose.orientation)
  return _internal_mutable_orientation();
}
inline void Pose::set_allocated_orientation(::proto::Quaternion* orientation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete orientation_;
  }
  if (orientation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(orientation);
    if (message_arena != submessage_arena) {
      orientation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, orientation, submessage_arena);
    }
    
  } else {
    
  }
  orientation_ = orientation;
  // @@protoc_insertion_point(field_set_allocated:proto.Pose.orientation)
}

// -------------------------------------------------------------------

// Joint

// repeated string name = 1;
inline int Joint::_internal_name_size() const {
  return name_.size();
}
inline int Joint::name_size() const {
  return _internal_name_size();
}
inline void Joint::clear_name() {
  name_.Clear();
}
inline std::string* Joint::add_name() {
  // @@protoc_insertion_point(field_add_mutable:proto.Joint.name)
  return _internal_add_name();
}
inline const std::string& Joint::_internal_name(int index) const {
  return name_.Get(index);
}
inline const std::string& Joint::name(int index) const {
  // @@protoc_insertion_point(field_get:proto.Joint.name)
  return _internal_name(index);
}
inline std::string* Joint::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:proto.Joint.name)
  return name_.Mutable(index);
}
inline void Joint::set_name(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:proto.Joint.name)
  name_.Mutable(index)->assign(value);
}
inline void Joint::set_name(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:proto.Joint.name)
  name_.Mutable(index)->assign(std::move(value));
}
inline void Joint::set_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.Joint.name)
}
inline void Joint::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.Joint.name)
}
inline std::string* Joint::_internal_add_name() {
  return name_.Add();
}
inline void Joint::add_name(const std::string& value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:proto.Joint.name)
}
inline void Joint::add_name(std::string&& value) {
  name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:proto.Joint.name)
}
inline void Joint::add_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:proto.Joint.name)
}
inline void Joint::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:proto.Joint.name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Joint::name() const {
  // @@protoc_insertion_point(field_list:proto.Joint.name)
  return name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Joint::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:proto.Joint.name)
  return &name_;
}

// repeated float position = 2;
inline int Joint::_internal_position_size() const {
  return position_.size();
}
inline int Joint::position_size() const {
  return _internal_position_size();
}
inline void Joint::clear_position() {
  position_.Clear();
}
inline float Joint::_internal_position(int index) const {
  return position_.Get(index);
}
inline float Joint::position(int index) const {
  // @@protoc_insertion_point(field_get:proto.Joint.position)
  return _internal_position(index);
}
inline void Joint::set_position(int index, float value) {
  position_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.Joint.position)
}
inline void Joint::_internal_add_position(float value) {
  position_.Add(value);
}
inline void Joint::add_position(float value) {
  _internal_add_position(value);
  // @@protoc_insertion_point(field_add:proto.Joint.position)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Joint::_internal_position() const {
  return position_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Joint::position() const {
  // @@protoc_insertion_point(field_list:proto.Joint.position)
  return _internal_position();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Joint::_internal_mutable_position() {
  return &position_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Joint::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:proto.Joint.position)
  return _internal_mutable_position();
}

// -------------------------------------------------------------------

// MocapKeypoints

// .proto.Header header = 1;
inline bool MocapKeypoints::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool MocapKeypoints::has_header() const {
  return _internal_has_header();
}
inline void MocapKeypoints::clear_header() {
  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::proto::Header& MocapKeypoints::_internal_header() const {
  const ::proto::Header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::proto::Header*>(
      &::proto::_Header_default_instance_);
}
inline const ::proto::Header& MocapKeypoints::header() const {
  // @@protoc_insertion_point(field_get:proto.MocapKeypoints.header)
  return _internal_header();
}
inline void MocapKeypoints::unsafe_arena_set_allocated_header(
    ::proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.MocapKeypoints.header)
}
inline ::proto::Header* MocapKeypoints::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::proto::Header* MocapKeypoints::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:proto.MocapKeypoints.header)
  
  ::proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::proto::Header* MocapKeypoints::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::proto::Header* MocapKeypoints::mutable_header() {
  // @@protoc_insertion_point(field_mutable:proto.MocapKeypoints.header)
  return _internal_mutable_header();
}
inline void MocapKeypoints::set_allocated_header(::proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:proto.MocapKeypoints.header)
}

// repeated .proto.Pose left_mocap_pose = 2;
inline int MocapKeypoints::_internal_left_mocap_pose_size() const {
  return left_mocap_pose_.size();
}
inline int MocapKeypoints::left_mocap_pose_size() const {
  return _internal_left_mocap_pose_size();
}
inline void MocapKeypoints::clear_left_mocap_pose() {
  left_mocap_pose_.Clear();
}
inline ::proto::Pose* MocapKeypoints::mutable_left_mocap_pose(int index) {
  // @@protoc_insertion_point(field_mutable:proto.MocapKeypoints.left_mocap_pose)
  return left_mocap_pose_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose >*
MocapKeypoints::mutable_left_mocap_pose() {
  // @@protoc_insertion_point(field_mutable_list:proto.MocapKeypoints.left_mocap_pose)
  return &left_mocap_pose_;
}
inline const ::proto::Pose& MocapKeypoints::_internal_left_mocap_pose(int index) const {
  return left_mocap_pose_.Get(index);
}
inline const ::proto::Pose& MocapKeypoints::left_mocap_pose(int index) const {
  // @@protoc_insertion_point(field_get:proto.MocapKeypoints.left_mocap_pose)
  return _internal_left_mocap_pose(index);
}
inline ::proto::Pose* MocapKeypoints::_internal_add_left_mocap_pose() {
  return left_mocap_pose_.Add();
}
inline ::proto::Pose* MocapKeypoints::add_left_mocap_pose() {
  // @@protoc_insertion_point(field_add:proto.MocapKeypoints.left_mocap_pose)
  return _internal_add_left_mocap_pose();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose >&
MocapKeypoints::left_mocap_pose() const {
  // @@protoc_insertion_point(field_list:proto.MocapKeypoints.left_mocap_pose)
  return left_mocap_pose_;
}

// repeated .proto.Pose right_mocap_pose = 3;
inline int MocapKeypoints::_internal_right_mocap_pose_size() const {
  return right_mocap_pose_.size();
}
inline int MocapKeypoints::right_mocap_pose_size() const {
  return _internal_right_mocap_pose_size();
}
inline void MocapKeypoints::clear_right_mocap_pose() {
  right_mocap_pose_.Clear();
}
inline ::proto::Pose* MocapKeypoints::mutable_right_mocap_pose(int index) {
  // @@protoc_insertion_point(field_mutable:proto.MocapKeypoints.right_mocap_pose)
  return right_mocap_pose_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose >*
MocapKeypoints::mutable_right_mocap_pose() {
  // @@protoc_insertion_point(field_mutable_list:proto.MocapKeypoints.right_mocap_pose)
  return &right_mocap_pose_;
}
inline const ::proto::Pose& MocapKeypoints::_internal_right_mocap_pose(int index) const {
  return right_mocap_pose_.Get(index);
}
inline const ::proto::Pose& MocapKeypoints::right_mocap_pose(int index) const {
  // @@protoc_insertion_point(field_get:proto.MocapKeypoints.right_mocap_pose)
  return _internal_right_mocap_pose(index);
}
inline ::proto::Pose* MocapKeypoints::_internal_add_right_mocap_pose() {
  return right_mocap_pose_.Add();
}
inline ::proto::Pose* MocapKeypoints::add_right_mocap_pose() {
  // @@protoc_insertion_point(field_add:proto.MocapKeypoints.right_mocap_pose)
  return _internal_add_right_mocap_pose();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Pose >&
MocapKeypoints::right_mocap_pose() const {
  // @@protoc_insertion_point(field_list:proto.MocapKeypoints.right_mocap_pose)
  return right_mocap_pose_;
}

// -------------------------------------------------------------------

// HandAction

// .proto.Header header = 1;
inline bool HandAction::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool HandAction::has_header() const {
  return _internal_has_header();
}
inline void HandAction::clear_header() {
  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::proto::Header& HandAction::_internal_header() const {
  const ::proto::Header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::proto::Header*>(
      &::proto::_Header_default_instance_);
}
inline const ::proto::Header& HandAction::header() const {
  // @@protoc_insertion_point(field_get:proto.HandAction.header)
  return _internal_header();
}
inline void HandAction::unsafe_arena_set_allocated_header(
    ::proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.HandAction.header)
}
inline ::proto::Header* HandAction::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::proto::Header* HandAction::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:proto.HandAction.header)
  
  ::proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::proto::Header* HandAction::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::proto::Header* HandAction::mutable_header() {
  // @@protoc_insertion_point(field_mutable:proto.HandAction.header)
  return _internal_mutable_header();
}
inline void HandAction::set_allocated_header(::proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:proto.HandAction.header)
}

// .proto.Joint joint_left = 2;
inline bool HandAction::_internal_has_joint_left() const {
  return this != internal_default_instance() && joint_left_ != nullptr;
}
inline bool HandAction::has_joint_left() const {
  return _internal_has_joint_left();
}
inline void HandAction::clear_joint_left() {
  if (GetArena() == nullptr && joint_left_ != nullptr) {
    delete joint_left_;
  }
  joint_left_ = nullptr;
}
inline const ::proto::Joint& HandAction::_internal_joint_left() const {
  const ::proto::Joint* p = joint_left_;
  return p != nullptr ? *p : *reinterpret_cast<const ::proto::Joint*>(
      &::proto::_Joint_default_instance_);
}
inline const ::proto::Joint& HandAction::joint_left() const {
  // @@protoc_insertion_point(field_get:proto.HandAction.joint_left)
  return _internal_joint_left();
}
inline void HandAction::unsafe_arena_set_allocated_joint_left(
    ::proto::Joint* joint_left) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(joint_left_);
  }
  joint_left_ = joint_left;
  if (joint_left) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.HandAction.joint_left)
}
inline ::proto::Joint* HandAction::release_joint_left() {
  auto temp = unsafe_arena_release_joint_left();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::proto::Joint* HandAction::unsafe_arena_release_joint_left() {
  // @@protoc_insertion_point(field_release:proto.HandAction.joint_left)
  
  ::proto::Joint* temp = joint_left_;
  joint_left_ = nullptr;
  return temp;
}
inline ::proto::Joint* HandAction::_internal_mutable_joint_left() {
  
  if (joint_left_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::Joint>(GetArena());
    joint_left_ = p;
  }
  return joint_left_;
}
inline ::proto::Joint* HandAction::mutable_joint_left() {
  // @@protoc_insertion_point(field_mutable:proto.HandAction.joint_left)
  return _internal_mutable_joint_left();
}
inline void HandAction::set_allocated_joint_left(::proto::Joint* joint_left) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete joint_left_;
  }
  if (joint_left) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(joint_left);
    if (message_arena != submessage_arena) {
      joint_left = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, joint_left, submessage_arena);
    }
    
  } else {
    
  }
  joint_left_ = joint_left;
  // @@protoc_insertion_point(field_set_allocated:proto.HandAction.joint_left)
}

// .proto.Joint joint_right = 3;
inline bool HandAction::_internal_has_joint_right() const {
  return this != internal_default_instance() && joint_right_ != nullptr;
}
inline bool HandAction::has_joint_right() const {
  return _internal_has_joint_right();
}
inline void HandAction::clear_joint_right() {
  if (GetArena() == nullptr && joint_right_ != nullptr) {
    delete joint_right_;
  }
  joint_right_ = nullptr;
}
inline const ::proto::Joint& HandAction::_internal_joint_right() const {
  const ::proto::Joint* p = joint_right_;
  return p != nullptr ? *p : *reinterpret_cast<const ::proto::Joint*>(
      &::proto::_Joint_default_instance_);
}
inline const ::proto::Joint& HandAction::joint_right() const {
  // @@protoc_insertion_point(field_get:proto.HandAction.joint_right)
  return _internal_joint_right();
}
inline void HandAction::unsafe_arena_set_allocated_joint_right(
    ::proto::Joint* joint_right) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(joint_right_);
  }
  joint_right_ = joint_right;
  if (joint_right) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.HandAction.joint_right)
}
inline ::proto::Joint* HandAction::release_joint_right() {
  auto temp = unsafe_arena_release_joint_right();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::proto::Joint* HandAction::unsafe_arena_release_joint_right() {
  // @@protoc_insertion_point(field_release:proto.HandAction.joint_right)
  
  ::proto::Joint* temp = joint_right_;
  joint_right_ = nullptr;
  return temp;
}
inline ::proto::Joint* HandAction::_internal_mutable_joint_right() {
  
  if (joint_right_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::Joint>(GetArena());
    joint_right_ = p;
  }
  return joint_right_;
}
inline ::proto::Joint* HandAction::mutable_joint_right() {
  // @@protoc_insertion_point(field_mutable:proto.HandAction.joint_right)
  return _internal_mutable_joint_right();
}
inline void HandAction::set_allocated_joint_right(::proto::Joint* joint_right) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete joint_right_;
  }
  if (joint_right) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(joint_right);
    if (message_arena != submessage_arena) {
      joint_right = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, joint_right, submessage_arena);
    }
    
  } else {
    
  }
  joint_right_ = joint_right;
  // @@protoc_insertion_point(field_set_allocated:proto.HandAction.joint_right)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sharpa_5fhand_2eproto
