# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sharpa_hand.proto
# Protobuf Python Version: 4.25.8
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sharpa_hand.proto\x12\x05proto\"%\n\x05Stamp\x12\x0b\n\x03sec\x18\x01 \x01(\x05\x12\x0f\n\x07nanosec\x18\x02 \x01(\x05\"7\n\x06Header\x12\x1b\n\x05stamp\x18\x01 \x01(\x0b\x32\x0c.proto.Stamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"8\n\nQuaternion\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"N\n\x04Pose\x12\x1e\n\x08position\x18\x01 \x01(\x0b\x32\x0c.proto.Point\x12&\n\x0borientation\x18\x02 \x01(\x0b\x32\x11.proto.Quaternion\"\'\n\x05Joint\x12\x0c\n\x04name\x18\x01 \x03(\t\x12\x10\n\x08position\x18\x02 \x03(\x02\"|\n\x0eMocapKeypoints\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.proto.Header\x12$\n\x0fleft_mocap_pose\x18\x02 \x03(\x0b\x32\x0b.proto.Pose\x12%\n\x10right_mocap_pose\x18\x03 \x03(\x0b\x32\x0b.proto.Pose\"p\n\nHandAction\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.proto.Header\x12 \n\njoint_left\x18\x02 \x01(\x0b\x32\x0c.proto.Joint\x12!\n\x0bjoint_right\x18\x03 \x01(\x0b\x32\x0c.proto.Jointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sharpa_hand_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STAMP']._serialized_start=28
  _globals['_STAMP']._serialized_end=65
  _globals['_HEADER']._serialized_start=67
  _globals['_HEADER']._serialized_end=122
  _globals['_POINT']._serialized_start=124
  _globals['_POINT']._serialized_end=164
  _globals['_QUATERNION']._serialized_start=166
  _globals['_QUATERNION']._serialized_end=222
  _globals['_POSE']._serialized_start=224
  _globals['_POSE']._serialized_end=302
  _globals['_JOINT']._serialized_start=304
  _globals['_JOINT']._serialized_end=343
  _globals['_MOCAPKEYPOINTS']._serialized_start=345
  _globals['_MOCAPKEYPOINTS']._serialized_end=469
  _globals['_HANDACTION']._serialized_start=471
  _globals['_HANDACTION']._serialized_end=583
# @@protoc_insertion_point(module_scope)
